### ISSUE TITLE
Use with other VPN

### ISSUE THREAD

**Issue by schoolprivacy** [anasfanani/Magisk-Tailscaled#12]
Hello

You mentioned on your new release this

> Other VPN
You need to use socks5 port 1099 for accessing other tailscale devices, or you can just route the ip with NekoBox and create a Warp Wireguard.

I have been trying to do this , but unable to .  Having some difficulty setting this up.
I have nekobox and set up Warp Wireguard, but i can not add 

> Manual Setting - SOCKS5
Server/Port: 127.0.0.1:1099
Name: TAILSCALE

As the warp wireguard is using this.

I can not add 

> Route - Add
IP: 100.64.0.0/10
Outbound: TAILSCALE

as the outbound would be warp wireguard, but i change the outbound to warp , it does not work.

Just wondered if you had an idea what i could do.

thanks

**Comment by anasfanani** [comment]
Create a two proxy, tailscale socks and generate a warp wireguard .

Create a route 100.64.0.0/10, outbound set to tailscale socks.



![Screenshot_2024-01-23-03-42-26-468_moe.nb4a.jpg](https://github.com/anasfanani/Magisk-Tailscaled/assets/135501348/25de3ee4-8321-46f6-ab7b-13a882a3e62e)


![Screenshot_2024-01-23-03-38-51-404_moe.nb4a.jpg](https://github.com/anasfanani/Magisk-Tailscaled/assets/135501348/9460eacb-d38a-48ea-b25a-90405945366d)

![Screenshot_2024-01-23-03-38-08-113_moe.nb4a.jpg](https://github.com/anasfanani/Magisk-Tailscaled/assets/135501348/eb17d287-2c6c-4ffc-9cf8-5a927e124087)

**Comment by schoolprivacy** [comment]
Thank you.  This is a game changer.  

Brilliant.

Also to add if other people have a look here, if you add a subnet, you also need to add a separate route that ip range as well for it to work.

**Comment by anasfanani** [comment]
You're welcome brother, personally I dont recomend to use nekobox for route, I prefer to use clash for route trafict based on ip range, the program run as root and can be set to use direct ( wifi network / data network without using any proxy ) except routed traffict ( tailscale subnet or other route (block ads,etc) ), as there already box manager app and have feature for toggle clash on or off from notification.
Setup a clash for first time is a bit headache ( I need 3 weeks for understanding with the config ), because the documentation is in chinesse language, but we can use google translate.
Anyway, clash is a powerfull software, I can route,manage multiple proxies, dns, cross device, etc. I'm using it in my android & home router.

**Comment by schoolprivacy** [comment]
Thanks, i did try clash but the language barrier was a huge minefield.
If you ever have time, a guide would be very helpful.
Thanks again.

**Comment by anasfanani** [comment]
I will create a config.yml for you, what do you need ? 
For basic tailscale routing & opotional vmess proxy ? or anything you want to add.

**Comment by schoolprivacy** [comment]
Hey.

Yes a basic tailscale and wireguard vpn. 

Thanks

**Comment by anasfanani** [comment]
I'm sorry for verry late reply, I have other work :( 
But just for inform you maybe still use tailscale module, check latest pre release at https://github.com/anasfanani/Magisk-Tailscaled/releases

You now can use direct connection to the tailscale IP

Let me close this issue, if you need help and discussion, come to telegram group brother.
I will do the best as I can for you.
