### ISSUE TITLE
Headscale Support

### ISSUE THREAD

**Issue by squidds** [anasfanani/Magisk-Tailscaled#14]
Does this module support a custom control server? I don't seem to be getting a response when using "`tailscale up --login-server=https://login.server.net`" or when using "`tailscale login --login-server=https://login.server.net`"

This works for all of the tailscale CLI implementations I have played around with so far. This would be a cool addition if it is not already supported in the app. Thank you.

**Comment by anasfanani** [comment]
> Does this module support a custom control server? I don't seem to be getting a response when using "`tailscale up --login-server=https://login.server.net`" or when using "`tailscale login --login-server=https://login.server.net`"

Did you mean using custom server like headscale ?

https://github.com/anasfanani/Magisk-Tailscaled/issues/4

I cant test it because I have problem with configuration headscale server.

**Comment by squidds** [comment]
If you want I can setup a test instance of headscale on a VPS for you to test on if you'd like

**Comment by squidds** [comment]
> > Does this module support a custom control server? I don't seem to be getting a response when using "`tailscale up --login-server=https://login.server.net`" or when using "`tailscale login --login-server=https://login.server.net`"
> 
> Did you mean using custom server like headscale ?
> 
> https://github.com/anasfanani/Magisk-Tailscaled/issues/4
> 
> I cant test it because I have problem with configuration headscale server.

Did you ever get headscale working?

**Comment by anasfanani** [comment]
> > > Does this module support a custom control server? I don't seem to be getting a response when using "`tailscale up --login-server=https://login.server.net`" or when using "`tailscale login --login-server=https://login.server.net`"
> > 
> > Did you mean using custom server like headscale ?
> > 
> > https://github.com/anasfanani/Magisk-Tailscaled/issues/4
> > 
> > I cant test it because I have problem with configuration headscale server.
> 
> Did you ever get headscale working? 

Please share basic headscale server config, so I can test it.
I have amazon aws free for test.

**Comment by unixfox** [comment]
looking at the logs it seems like tailscale cannot find the DNS entry:
```
2024/03/10 14:41:23 [RATELIMIT] format("monitor: %s: src=%v, dst=%v, gw=%v, outif=%v, table=%v")
2024/03/10 14:41:24 Received error: fetch control key: Get "https://headscale.example.eu/key?v=87": failed to resolve "headscale.example.eu": no DNS fallback candidates remain for "headscale.example.eu"
2024/03/10 14:41:26 control: LoginInteractive -> regen=true
2024/03/10 14:41:26 control: doLogin(regen=true, hasUrl=false)
```

Maybe the daemon does not use the default DNS server in android?

**Comment by probablypablito** [comment]
Thank you for the Coredns tip! Worked like a charm.

**Comment by anasfanani** [comment]
I test tailscale magisk with headscale custom url and works as expected, I close this issue.
Thankyou

**Comment by bioluks** [comment]
Sadly I have to reopen this issue, I'm seeing IPv6 addresses everywhere in the logs, my current location has no IPv6 support, so I'm getting the same errors, seeing lines like:
```
2024/04/28 21:41:53 control: bootstrapDNS("derp8b.tailscale.com", "2a03:b0c0:1:d0::ec1:e001") for "headscale.example.com" error: Get "https://derp8b.tailscale.com/bootstrap-dns?q=headscale.example.com": dial tcp [2a03:b0c0:1:d0::ec1:e001]:443: connect: network is unreachable
2024/04/28 21:41:53 [RATELIMIT] format("control: bootstrapDNS(%q, %q) for %q error: %v")
2024/04/28 21:41:55 Received error: fetch control key: Get "https://headscale.example.com/key?v=90": failed to resolve "headscale.example.com": no DNS fallback candidates remain for "headscale.example.com"
2024/04/28 21:42:12 [RATELIMIT] format("monitor: ip rule deleted; failed to parse netlink message: %v") (33 dropped)
2024/04/28 21:42:12 monitor: ip rule deleted; failed to parse netlink message: invalid route message attributes: netlink: attribute 20 is not a uint8; length: 8
2024/04/28 21:42:12 monitor: ip rule deleted; failed to parse netlink message: invalid route message attributes: netlink: attribute 20 is not a uint8; length: 8
2024/04/28 21:42:12 monitor: ip rule deleted; failed to parse netlink message: invalid route message attributes: netlink: attribute 20 is not a uint8; length: 8
2024/04/28 21:42:12 monitor: ip rule deleted; failed to parse netlink message: invalid route message attributes: netlink: attribute 20 is not a uint8; length: 8
2024/04/28 21:42:15 monitor: ip rule deleted; failed to parse netlink message: invalid route message attributes: netlink: attribute 20 is not a uint8; length: 8
2024/04/28 21:42:15 [RATELIMIT] format("monitor: ip rule deleted; failed to parse netlink message: %v")
2024/04/28 21:42:20 control: LoginInteractive -> regen=true
2024/04/28 21:42:20 control: doLogin(regen=true, hasUrl=false)
2024/04/28 21:42:20 [RATELIMIT] format("control: trying bootstrapDNS(%q, %q) for %q ...") (9 dropped)
2024/04/28 21:42:21 control: trying bootstrapDNS("derp1d.tailscale.com", "2604:a880:800:10::7fe:f001") for "headscale.example.com" ...
2024/04/28 21:42:21 [RATELIMIT] format("control: bootstrapDNS(%q, %q) for %q error: %v") (3 dropped)
2024/04/28 21:43:27 control: bootstrapDNS("derp8c.tailscale.com", "2a03:b0c0:1:d0::e1f:4001") for "headscale.example.com" error: Get "https://derp8c.tailscale.com/bootstrap-dns?q=headscale.example.com": dial tcp [2a03:b0c0:1:d0::e1f:4001]:443: connect: network is unreachable
2024/04/28 21:43:27 control: trying bootstrapDNS("derp1d.tailscale.com", "165.22.33.71") for "headscale.example.com" ...
2024/04/28 21:43:27 [RATELIMIT] format("control: trying bootstrapDNS(%q, %q) for %q ...")
```
`headscale.example.com` is for privacy of course. Even when having a hosts file entry in Android nothing seems to solve this issue.
The derp servers used in the 'trying bootstrapDNS' lines are returning IPv6 addresses first, the IPv4 addresses come later... A picture from the bootstrapDNS request:

![image](https://github.com/anasfanani/Magisk-Tailscaled/assets/30238916/6e86f85f-dd1f-4ea1-82f9-2fd5d39cee19)

First I thought this is a tailscale issue on its own, but since this does not happen on desktop clients I thought we can think of a workaround for the Magisk/KSU module. Things coming to my mind I still have to test:

1. Reversing the bootstrap DNS results, so the IPv4 addresses would be on top of the list (?)
2. Hardcoding the DERP servers with their IP's temporarily into the hosts file systemlessly until we register the device as a node on headscale.
3. Telling Tailscale with a commandline switch (if this exists of course) that it should prefer IPv4 over IPv6.
4. Using a HTTPS_PROXY or HTTPS_PROXY until registered as a node. Tailscale has issues from time to time recognizing these environment variables. See [related Reddit Post](https://www.reddit.com/r/Tailscale/comments/16ngi3x/how_to_tell_tailscaled_about_my_http_proxy/) with the same issue I have. 

These are probably not that logical and promising but it's better than not being able to register the device at all. Also a related [GitHub issue on `tailscale/tailscale`](https://github.com/tailscale/tailscale/issues/5853).
