### ISSUE TITLE
curl not found

### ISSUE THREAD

**Issue by tiann** [anasfanani/Magisk-Tailscaled#2]
Some device doesn't have `curl`, this would fail forever: https://github.com/anasfanani/Magisk-Tailscaled/blob/main/service.sh#L8C5-L8C21

maybe we can simply use `ping -c 1.1.1.1`?

By the way, this module is proved to work well on KernelSU after commit: https://github.com/anasfanani/Magisk-Tailscaled/commit/6c86fd1eb5de062892af535ad7402cc3be44f157 ;) You don't need to create a module for it separately, it  is compatible with Magisk module.

**Comment by anasfanani** [comment]
> Some device doesn't have `curl`, this would fail forever: https://github.com/anasfanani/Magisk-Tailscaled/blob/main/service.sh#L8C5-L8C21
> maybe we can simply use `ping -c 1.1.1.1`?

I have implement to use ping [here](https://github.com/anasfanani/Magisk-Tailscaled/commit/ba87ab91948f3161a4b21428fee4a0aae122634a#diff-bf11ea34921c7e6431aa53e644fb47a0262cdefd358563867cea5d7551916df2R8), but some people in social media, suggest me to use `curl`, some device would fail because can't use ICMP,  example : people with proxy tools called `openclash`, `sing-box`, box for magisk, clash for magisk,I agree with them because I have also experienced ping failure but not with curl.
As far I know , the magisk `service.sh` will executed in the ash shell of BusyBox, every single command will directly use the applet within BusyBox, then I check in the `/data/adb/magisk/busybox` have `wget` applet, maybe I can use `wget` instead of `ping` ?
I also think whether internet check is needed or not, I need to confirm it, if not needed, then I can delete the internet check.

> By the way, this module is proved to work well on KernelSU after commit: [6c86fd1](https://github.com/anasfanani/Magisk-Tailscaled/commit/6c86fd1eb5de062892af535ad7402cc3be44f157) ;) You don't need to create a module for it separately, it is compatible with Magisk module.


Thankyou, I will update the README.md later.

**Comment by tiann** [comment]
> As far I know , the magisk `service.sh` will executed in the ash shell of BusyBox, every single command will directly use the applet within BusyBox, then I check in the `/data/adb/magisk/busybox` have `wget` applet, maybe I can use `wget` instead of `ping` ?

I think `wget` is a good solution. And KernelSU has the same behavior, it will work too.

**Comment by anasfanani** [comment]
> I think `wget` is a good solution. And KernelSU has the same behavior, it will work too.


I have tested to remove the internet connection check before running tailscaled, apparently it has no effect at all, I will remove this unnecessary internet check because tailscaled will connect automatically if internet is available.

Anyway, thanks for your feedback, I just found out you own the KernelSU repository, it's an honor to get feedback from you.

**Comment by tiann** [comment]
Thank you for the amazing module, it is really helpful :)

**Comment by anasfanani** [comment]
> Thank you for the amazing module, it is really helpful :)

You're welcome, I fix some some problem, can you try this https://github.com/anasfanani/Magisk-Tailscaled/releases/tag/v1.56.1.2-beta

**Comment by tiann** [comment]
> > Thank you for the amazing module, it is really helpful :)
> 
> You're welcome, I fix some some problem, can you try this https://github.com/anasfanani/Magisk-Tailscaled/releases/tag/v1.56.1.2-beta

It works as expected.
