### ISSUE TITLE
Documentation for how to actually access tailscale using this?

### ISSUE THREAD

**Issue by Chloe-ko** [anasfanani/Magisk-Tailscaled#5]
Hey,

sorry if an issue isn't a suitable place to ask this, but:
In another issue it was mentioned you use Box for Magisk proxy tool in order to access the userspace tailscale: https://github.com/anasfanani/Magisk-Tailscaled/issues/1#issuecomment-1855286194

I am trying to do the same, but I struggle to get it to work. Could you maybe share configuration examples (or add them to the README?) of your configuration for box for magisk and how to use it with this module?

Thanks and happy new year

**Comment by anasfanani** [comment]
> I run with -tun=userspace-networking because I'm run with proxy tool

Em... Recently... I'm not sure about my statement, I thought I was using `tun=userspace-networking` because I was using a proxy tool, apparently after I tried it myself without activating `clash` core (in this case if that means the proxy tool) , and without using `tun=userspace-networking` , tailscaled cannot connect to the internet.

I dont know why, but after using a `tun=userspace`, tailscale can run and connect.

According to the [documentation](https://tailscale.com/kb/1112/userspace-networking), if we use `tun=userspace-networking` , then use the parameter
`--socks5-server=localhost:1055 --outbound-http-proxy-listen=localhost:1055` for the listening.

This port can be used in applications that want to use a tailscale network.


> I am trying to do the same, but I struggle to get it to work.

What are you trying ? 
Here my experience about using this tailscale, first of all I always use `clash`, then I want to use Tailscale to remote my cellphone, I think it won't work if 2 VPNs on Android are connected together, I tried using `userspace networking` because I use `clash` on Android.
But recently I discovered that Tailscale cannot connect to the network on Android if I don't use `userspace networking`.

> Thanks and happy new year

Yeah you're welcome, happy new year too.

**Comment by Chloe-ko** [comment]
Yeah, I had the same experience - I actually made a fork of your module and compiled it without userspace-networking, but then it just couldn't connect to the internet.

> --socks5-server=localhost:1055 --outbound-http-proxy-listen=localhost:1055

I did try the argument for the socks5-server, but failed to connect to the local socks5 proxy (even after confirming that tailscale listens on port 1055) and I'm not sure yet why. I was assuming you'd have done the same, which is why I asked for the configuration example.. Since box for magisk / clash can be used to proxy connections via a socks5 server.

> What are you trying ?

I am trying to access other tailscale devices _from_ my phone. Accessing my phone from other devices works fine, but I want to be able to do the opposite :(

**Comment by schoolprivacy** [comment]
I am having the same problem.
Using nekobox on lineageos. I can connect to the android device via other connected devices, but my android can not connect to other devixes.

**Comment by anasfanani** [comment]
Since I'm using fake ping, I dont know if the connection from android to other tailscale device wont work. 

I just test ping then see reply, I think work, but I forgot even I ping nonexistent IP always return reply.

Well thankyou for the report, I will investigate the problem.

**Comment by tripplehelix** [comment]
> I am trying to access other tailscale devices _from_ my phone. Accessing my phone from other devices works fine, but I want to be able to do the opposite :(

I was having the same issue, I opened a new issue as it's not related to documentation

**Comment by anasfanani** [comment]
I found clue for work with clash proxy.

```
#!/system/bin/sh
if [ $# -eq 0 ]; then # if no arguments are passed, start tailscaled
    export PATH=/data/adb/tailscale/bin:$PATH
    export HOME=/data/adb/tailscale/tmp/
    export HTTP_PROXY=socks5://127.0.0.1:7890 HTTPS_PROXY=socks5://127.0.0.1:7890
    /data/adb/tailscale/bin/tailscaled -verbose=0 --outbound-http-proxy-listen=localhost:1099 --socks5-server=localhost:1099 -tun=userspace-networking -statedir=/data/adb/tailscale/tmp/ -state=/data/adb/tailscale/tmp/tailscaled.state -socket=/data/adb/tailscale/tmp/tailscaled.sock -port=41641
else # otherwise, run tailscale with the arguments passed
    /data/adb/tailscale/bin/tailscaled "$@"
fi
```
Socks5 clash is running on port 7890

![Screenshot_2024-01-07-02-47-23-478_xyz.chz.bfm.jpg](https://github.com/anasfanani/Magisk-Tailscaled/assets/135501348/e34d2044-8e6f-4d55-9dd7-6f005042705c)

For connecting other tailscale device, use tailscale socks5/proxy running on port 1099, as example, there already running IIS Windows Server on my other tailscale device. 

Use `curl OTHER_TAILSCALE_IP -x localhost:1099` for test connection.


```
┌──(anasfanani@localhost)-[~]
└─$ curl -v 100.93.168.40 -x localhost:1099
*   Trying [::1]:1099...
*   Trying 127.0.0.1:1099...
* Connected to localhost (127.0.0.1) port 1099
> GET http://100.93.168.40/ HTTP/1.1
> Host: 100.93.168.40
> User-Agent: curl/8.4.0
> Accept: */*
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Content-Length: 703
< Content-Type: text/html
< Date: Sat, 06 Jan 2024 19:40:12 GMT
< Etag: "8b4a69f5342eda1:0"
< Last-Modified: Thu, 14 Dec 2023 02:26:35 GMT
< Server: Microsoft-IIS/10.0
<
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>IIS Windows Server</title>
<style type="text/css">
<!--
body {
        color:#000000;
        background-color:#0072C6;
        margin:0;
}

#container {
        margin-left:auto;
        margin-right:auto;
        text-align:center;
        }

a img {
        border:none;
}

-->
</style>
</head>
<body>
<div id="container">
<a href="http://go.microsoft.com/fwlink/?linkid=66138&amp;clcid=0x409"><img src="iisstart.png" alt="IIS" width="960" height="600" /></a>
</div>
</body>
* Connection #0 to host localhost left intact
</html>┌──(anasfanani@localhost)-[~]
└─$
```

If want to make auto route for tailscale ip for clash, create rules for that.

Proxies section:
```
proxies:
  - name: "tailscale-socks"
    type: socks5
    server: localhost
    port: 1099
```
Rules section:
```
rules:
  - IP-CIDR,100.64.0.0/10,tailscale-socks
```



Then I can access to tailscale ip without specify proxy, an example, access tailscale IP from browser :

![Screenshot_2024-01-07-03-31-01-284_com.android.chrome.jpg](https://github.com/anasfanani/Magisk-Tailscaled/assets/135501348/3d56af13-299a-4b3d-a017-b9a47b74de03)


But I have other problem, when clash is disconnected, tailscaled wont connect, yea because I'm using `HTTP_PROXY` for running tailscaled. 

I set a rule for clash.

```
- OR,((PROCESS-NAME,tailscaled),(PROCESS-NAME,tailscale)),GLOBAL
```
Then delete the `HTTP_PROXY` line from tailscaled.

Still wont connect, this likely because tailscaled try to use dns server on localhost port :53.

```
logtail: dial "log.tailscale.io:443" failed: dial tcp: lookup log.tailscale.io on [::1]:53: read udp [fe80::86fe:9585:10d1:5405]:46861->[::1]:53: i/o timeout (in 10.006s)
```

I change the dns section in clash config.
Before :
```
listen: 0.0.0.0:1053
```
After :
```
listen: 0.0.0.0:53
```


Conclusion :

For best practice, I suggest to use this method. 

`/data/adb/modules/magisk-tailscaled/system/bin/tailscaled` :

```
#!/system/bin/sh
if [ $# -eq 0 ]; then # if no arguments are passed, start tailscaled
    export PATH=/data/adb/tailscale/bin:$PATH
    export HOME=/data/adb/tailscale/tmp/
    /data/adb/tailscale/bin/tailscaled -verbose=0 --outbound-http-proxy-listen=localhost:1099 --socks5-server=localhost:1099 -tun=userspace-networking -statedir=/data/adb/tailscale/tmp/ -state=/data/adb/tailscale/tmp/tailscaled.state -socket=/data/adb/tailscale/tmp/tailscaled.sock -port=41641
else # otherwise, run tailscale with the arguments passed
    /data/adb/tailscale/bin/tailscaled "$@"
fi
```

Clash Configuration :

Dns :
```
listen: 0.0.0.0:53
```
Proxies :
```
  - name: "tailscale-socks"
    type: socks5
    server: localhost
    port: 1099
```

Rule :
```
- IP-CIDR,100.64.0.0/10,tailscale-socks
- OR,((PROCESS-NAME,tailscaled),(PROCESS-NAME,tailscale)),GLOBAL
```

NekoBox Configuration :

Manual Setting > SOCKS5 

![Screenshot_2024-01-07-04-36-19-564_moe.nb4a.jpg](https://github.com/anasfanani/Magisk-Tailscaled/assets/135501348/66d7b7d4-d556-4bb1-8238-8c0601969143)

Route > Add :

![Screenshot_2024-01-07-04-40-41-343_moe.nb4a.jpg](https://github.com/anasfanani/Magisk-Tailscaled/assets/135501348/1e6a5b4d-7de9-4676-a6b4-2755a612d7be)


Reference :

IP 100.x.x.x 
https://tailscale.com/kb/1015/100.x-addresses

Nekobox Configuration
https://matsuridayo.github.io/nb4a-route/

~~Clash~~ Mihomo Configuration
https://wiki.metacubex.one/config/
https://github.com/taamarin/box_for_magisk/blob/master/box/clash/config.yaml


Notes :

For easy run and show response from tailscaled command, I've disable the magisk module, then navigate to path `/data/adb/modules/magisk-tailscaled/system/bin`.
Then run directly with `./tailscaled`

Recomended file manager and text editor : https://mixplorer.com/

Also we need to adjust service.sh for best practice, restart tailscaled, stop tailscaled, clear log, show live log.
Please make PR.

**Comment by schoolprivacy** [comment]
Just to add, changing to 1099 socks with above help.
I have my commerical vpn on using nekobox, and i used proxydroid to add the tailscale proxy to apps to use tailscale like connectbox and it works. 
Finally able to communicate from android to my other tailscale devices

**Comment by tripplehelix** [comment]
Would prefer the default configuration when installed to allow the phone to see other servers on the Tailscale network. Just randomly following instructions like this without any idea what it's doing doesn't give me hope.

**Comment by jiz4oh** [comment]
I also faced the issue


>Still wont connect, this likely because tailscaled try to use dns server on localhost port :53.
>```
>logtail: dial "log.tailscale.io:443" failed: dial tcp: lookup log.tailscale.io on [::1]:53: read udp >[fe80::86fe:9585:10d1:5405]:46861->[::1]:53: i/o timeout (in 10.006s)
>```

and I solved it by put fllowing codes in `/etc/resolv.conf`

```
nameserver 8.8.8.8
```

**Comment by anasfanani** [comment]
This should fix the existing problem, I've also added some shell scripts to control the daemon.
https://github.com/anasfanani/Magisk-Tailscaled/releases/tag/v1.56.1.3

I will close this issue, if you are still having problems, please reopen it. Thank you and don't forget to give ⭐ if this module is useful for you.
